-- Blog CMS schema for Online Manipal admin panel.
-- Run in Hostinger phpMyAdmin (SQL tab) against the same database used by public/api.

CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(150) DEFAULT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'editor',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_authors (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  bio TEXT DEFAULT NULL,
  image VARCHAR(500) DEFAULT NULL,
  page_url VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  description VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_tags (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(120) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blogs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt VARCHAR(500) DEFAULT NULL,
  content LONGTEXT DEFAULT NULL,
  toc JSON DEFAULT NULL,
  feature_image VARCHAR(500) DEFAULT NULL,
  feature_image_alt VARCHAR(255) DEFAULT NULL,
  feature_image_title VARCHAR(255) DEFAULT NULL,
  meta_title VARCHAR(255) DEFAULT NULL,
  meta_description VARCHAR(500) DEFAULT NULL,
  focus_keyword VARCHAR(150) DEFAULT NULL,
  primary_keyword VARCHAR(150) DEFAULT NULL,
  author_id INT UNSIGNED DEFAULT NULL,
  category_ids JSON DEFAULT NULL,
  status ENUM('draft','pending','published','scheduled','deleted') NOT NULL DEFAULT 'draft',
  publish_date DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  og_image VARCHAR(500) DEFAULT NULL,
  canonical_url VARCHAR(500) DEFAULT NULL,
  schema_json JSON DEFAULT NULL,
  views INT UNSIGNED NOT NULL DEFAULT 0,
  read_time INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_status (status),
  KEY idx_author (author_id),
  CONSTRAINT fk_blogs_author FOREIGN KEY (author_id) REFERENCES blog_authors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_tag_relations (
  blog_id INT UNSIGNED NOT NULL,
  tag_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (blog_id, tag_id),
  CONSTRAINT fk_rel_blog FOREIGN KEY (blog_id) REFERENCES blogs(id) ON DELETE CASCADE,
  CONSTRAINT fk_rel_tag FOREIGN KEY (tag_id) REFERENCES blog_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- No admin_users row is seeded here on purpose: a real bcrypt password hash
-- must be generated by PHP on the server. After running this schema, open
-- /admin/setup.php once in your browser to create the first admin user,
-- then delete setup.php.

-- Seed a default category and author so the editor isn't empty on first use.
INSERT INTO blog_categories (name, slug, description, is_active)
VALUES ('General', 'general', 'Default category', 1)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO blog_authors (name, bio, is_active)
VALUES ('Online Manipal Team', 'Editorial team at Online Manipal.', 1)
ON DUPLICATE KEY UPDATE name = name;

